import {JSX} from 'react'
import {
  AiML,
  AllCategories,
  Architecture,
  Career,
  Cases,
  Datas,
  Development,
  OpenSource,
  Safety,
  UI,
} from '@/assets/svg'

export type CategoriesTagsType = {
  name: string
  svg?: JSX.Element
  tags?: string[]
  to?: string
}

export const categoriesTags: CategoriesTagsType[] = [
  {
    name: 'Все категории',
    svg: <AllCategories />,
  },
  {
    name: 'Архитектура',
    svg: <Architecture />,
    tags: [
      'Open Source',
      'Программирование',
      'Алгоритмы',
      'Управление продуктом',
      'SaaS',
      'Хранение данных',
      'Информационная безопасность',
      'Веб-разработка',
    ],
  },
  {
    name: 'Данные',
    svg: <Datas />,
    tags: [
      'SQL',
      'Программирование',
      'Алгоритмы',
      'Управление продуктом',
      'PostgreSQL',
      'Хранение данных',
      'Математика',
      'PHP',
      'Python',
      'Тестирование',
      'Информационная безопасность',
      'Веб-разработка',
    ],
  },
  {
    name: 'Карьера',
    svg: <Career />,
    tags: [
      'JavaScript',
      'Программирование',
      'Алгоритмы',
      'Управление продуктом',
      'Хранение данных',
      'Математика',
      'AI',
      'Машинное обучение',
      'Python',
      'Веб-разработка',
    ],
  },
  {
    name: 'Разработка',
    svg: <Development />,
    tags: [
      'Веб-разработка',
      'iOS',
      'Open Source',
      'JavaScript',
      'SQL',
      'Java',
      'Программирование',
      'Алгоритмы',
      'Управление продуктом',
      'Agile',
      'SaaS',
      'HTML',
      'Хранение данных',
      'TypeScript',
      'C#',
      'Математика',
      'API',
      'Git',
      'AI',
      'PHP',
      'Машинное обучение',
      'Разработка игр',
      'Python',
      'Тестирование',
      'GitHub',
      'Информационная безопасность',
    ],
  },
  {
    name: 'AI/ML',
    svg: <AiML />,
    tags: [
      'Open Source',
      'Программирование',
      'Алгоритмы',
      'Управление продуктом',
      'AI',
      'Машинное обучение',
      'Веб-разработка',
    ],
  },
  {
    name: 'Open Source',
    svg: <OpenSource />,
    tags: [
      'Open Source',
      'JavaScript',
      'SQL',
      'Java',
      'Программирование',
      'Управление продуктом',
      'PostgreSQL',
      'Хранение данных',
      'TypeScript',
      'Git',
      'AI',
      'Swift',
      'PHP',
      'Смартфоны',
      'Разработка игр',
      'Python',
      'GitHub',
      'Информационная безопасность',
      'Веб-разработка',
    ],
  },
  {name: 'UX/UI', svg: <UI />, tags: ['Веб-разработка']},
  {name: 'Кейсы', svg: <Cases />},
  {name: 'Безопасность', svg: <Safety />},
]
